name       : hugo
version    : 0.94.0
release    : 130
source     :
    - https://github.com/gohugoio/hugo/archive/refs/tags/v0.94.0.tar.gz : 76f6ee1f9138c7f5562f02679576889d0087910c9a6e49ef16a5ebbefda9e917
license    : Apache-2.0
homepage   : https://gohugo.io
component  : programming
networking : yes
extract    : no
summary    : Hugo is a static HTML and CSS website generator written in Go.
description: |
    Hugo is a static HTML and CSS website generator written in Go.
builddeps  :
    - git
    - mage
setup      : |
    mkdir -p src/github.com/gohugoio/hugo
    tar xf $sources/v${version}.tar.gz -C src/github.com/gohugoio/hugo --strip-components 1
build      : |
    cd ..
    export GO111MODULE=on
    export HUGO_BUILD_TAGS=extended
    export GOPATH=`pwd`
    export PATH=$PATH:$GOPATH:$GOPATH/bin/
    cd src/github.com/gohugoio/hugo
    mage hugo
install    : |
    cd src/github.com/gohugoio/hugo/
    install -Dm00755 hugo $installdir/usr/bin/hugo
