name       : hugo
version    : 0.116.1
release    : 143
source     :
    - https://github.com/gohugoio/hugo/archive/refs/tags/v0.116.1.tar.gz : 6eea7a6e7630dc9fb04b64e59d987d738363e618521a5780b98db3058353a656
license    : Apache-2.0
homepage   : https://gohugo.io
component  : programming
networking : yes
extract    : no
summary    : Hugo is a static HTML and CSS website generator written in Go.
description: |
    Hugo is a static HTML and CSS website generator written in Go.
builddeps  :
    - golang
setup      : |
    mkdir -p src/github.com/gohugoio/hugo
    tar xf $sources/v${version}.tar.gz -C src/github.com/gohugoio/hugo --strip-components 1
build      : |
    cd ..
    export GO111MODULE=on
    export GOPATH=`pwd`
    export PATH=$PATH:$GOPATH:$GOPATH/bin/
    cd src/github.com/gohugoio/hugo
    go build -tags extended
install    : |
    cd src/github.com/gohugoio/hugo/
    install -Dm00755 hugo $installdir/usr/bin/hugo
