name       : hugo
version    : 0.104.2
release    : 137
source     :
    - https://github.com/gohugoio/hugo/archive/refs/tags/v0.104.2.tar.gz : 22ba682f30e4a3e2511662b5b223a15af0272d863d46276a5311cd15588848dd
license    : Apache-2.0
homepage   : https://gohugo.io
component  : programming
networking : yes
extract    : no
summary    : Hugo is a static HTML and CSS website generator written in Go.
description: |
    Hugo is a static HTML and CSS website generator written in Go.
builddeps  :
    - golang
setup      : |
    mkdir -p src/github.com/gohugoio/hugo
    tar xf $sources/v${version}.tar.gz -C src/github.com/gohugoio/hugo --strip-components 1
build      : |
    cd ..
    export GO111MODULE=on
    export HUGO_BUILD_TAGS=extended
    export GOPATH=`pwd`
    export PATH=$PATH:$GOPATH:$GOPATH/bin/
    cd src/github.com/gohugoio/hugo
    go build
install    : |
    cd src/github.com/gohugoio/hugo/
    install -Dm00755 hugo $installdir/usr/bin/hugo
