name       : hugo
version    : 0.20.6
release    : 13
source     :
    - https://github.com/spf13/hugo/archive/v0.20.6.tar.gz : 857655b69fb3e7f174011fd6774501194f1241bbb833256fd63b585b6d7a3cc0
license    : Apache-2.0
component  : programming
networking : yes
extract    : no
summary    : Hugo is a static HTML and CSS website generator written in Go.
description: |
    Hugo is a static HTML and CSS website generator written in Go.
builddeps  :
    - git
    - golang
setup      : |
    mkdir {bin,pkg,src}
    mkdir -p src/github.com/spf13/
    tar xf $sources/v$version.tar.gz -C src/github.com/spf13/
    cd src/github.com/spf13/
    mv hugo-$version hugo
build      : |
    export GOPATH=$workdir/
    export PATH=$PATH:$GOPATH:$GOPATH/bin/
    # Workaround failing to fetch yaml.v2
    go get github.com/go-yaml/yaml
    mkdir -p .cache/govendor/gopkg.in/
    mv src/github.com/go-yaml/yaml .cache/govendor/gopkg.in/yaml.v2
    # Continue on with build
    cd src/github.com/spf13/hugo/
    make govendor
    make no-git-info
install    : |
    cd src/github.com/spf13/hugo/
    install -Dm00755 hugo $installdir/usr/bin/hugo
