name       : hugo
version    : '0.38'
release    : 39
source     :
    - https://github.com/gohugoio/hugo/archive/v0.38.tar.gz : 08549563b718cc904e9a71b084f975b4b1fe05ab431e1258cbae23d4b76846ab
license    : Apache-2.0
component  : programming
networking : yes
extract    : no
summary    : Hugo is a static HTML and CSS website generator written in Go.
description: |
    Hugo is a static HTML and CSS website generator written in Go.
builddeps  :
    - git
    - mage
setup      : |
    mkdir -p src/github.com/gohugoio/hugo
    tar xf $sources/v${version}.tar.gz -C src/github.com/gohugoio/hugo --strip-components 1
build      : |
    cd ..
    export GOPATH=`pwd`
    export PATH=$PATH:$GOPATH:$GOPATH/bin/
    go get -u -v github.com/golang/dep/cmd/dep
    cd src/github.com/gohugoio/hugo
    mage vendor
    mage hugo
install    : |
    cd src/github.com/gohugoio/hugo/
    install -Dm00755 hugo $installdir/usr/bin/hugo
