name       : hugo
version    : '0.33'
release    : 32
source     :
    - https://github.com/gohugoio/hugo/archive/v0.33.tar.gz : 689164eaaf5c7016574036d8977a35bed58a7fbd2b178e8205a426116e5b94d0
license    : Apache-2.0
component  : programming
networking : yes
extract    : no
summary    : Hugo is a static HTML and CSS website generator written in Go.
description: |
    Hugo is a static HTML and CSS website generator written in Go.
builddeps  :
    - git
    - mage
setup      : |
    mkdir -p src/github.com/gohugoio/hugo
    tar xf $sources/v${version}.tar.gz -C src/github.com/gohugoio/hugo --strip-components 1
    cd src/github.com/gohugoio/hugo
    %patch -p1 < $pkgfiles/0001-Revert-Support-offline-builds.patch
build      : |
    cd ..
    export GOPATH=`pwd`
    export PATH=$PATH:$GOPATH:$GOPATH/bin/
    go get -u -v github.com/golang/dep/cmd/dep
    cd src/github.com/gohugoio/hugo
    mage hugo
install    : |
    cd src/github.com/gohugoio/hugo/
    install -Dm00755 hugo $installdir/usr/bin/hugo
