name       : hugo
version    : 0.18
release    : 3
source     :
    - https://github.com/spf13/hugo/releases/download/v0.18/hugo_0.18_Linux-64bit.tar.gz : 9993f091dd3614401627a926571fb9f057f26c6d584581d79fc6c43fca436640
license    : Apache-2.0
component  : programming
summary    : Hugo is a static HTML and CSS website generator written in Go.
description: |
    Hugo is a static HTML and CSS website generator written in Go.
install    : |
    install -Dm00755 hugo_0.18_linux_amd64 $installdir/usr/bin/hugo
