name       : hugo
version    : 0.17.0
release    : 2
source     :
    - https://github.com/spf13/hugo/releases/download/v0.17/hugo_0.17_Linux-64bit.tar.gz : f1467e204cc469b9ca6f17c0dc4da4a620643b6d9a50cb7dce2508aaf8fbc1ea
license    : Apache-2.0
component  : programming
summary    : Hugo is a static HTML and CSS website generator written in Go.
description: |
    Hugo is a static HTML and CSS website generator written in Go.
install    : |
    install -Dm00755 hugo_0.17_linux_amd64 $installdir/usr/bin/hugo
