name       : hugo
version    : 0.59.1
release    : 77
source     :
    - https://github.com/gohugoio/hugo/archive/v0.59.1.tar.gz : 5d1e21f97eca611b92ce511f8ee846b289a9484262d4ef646c9c5477ba97e7ce
license    : Apache-2.0
component  : programming
networking : yes
extract    : no
summary    : Hugo is a static HTML and CSS website generator written in Go.
description: |
    Hugo is a static HTML and CSS website generator written in Go.
builddeps  :
    - git
    - mage
setup      : |
    mkdir -p src/github.com/gohugoio/hugo
    tar xf $sources/v${version}.tar.gz -C src/github.com/gohugoio/hugo --strip-components 1
build      : |
    cd ..
    export GO111MODULE=on
    export HUGO_BUILD_TAGS=extended
    export GOPATH=`pwd`
    export PATH=$PATH:$GOPATH:$GOPATH/bin/
    cd src/github.com/gohugoio/hugo
    mage hugo
install    : |
    cd src/github.com/gohugoio/hugo/
    install -Dm00755 hugo $installdir/usr/bin/hugo
