name       : hugo
version    : 0.27.1
release    : 22
source     :
    - https://github.com/gohugoio/hugo/archive/v0.27.1.tar.gz : b357b4e3edd8934dbbbc6a04b57a36c07f1923ac3891b6f822fadd48ccaaeaba
license    : Apache-2.0
component  : programming
networking : yes
extract    : no
summary    : Hugo is a static HTML and CSS website generator written in Go.
description: |
    Hugo is a static HTML and CSS website generator written in Go.
builddeps  :
    - git
    - golang
setup      : |
    mkdir {bin,pkg,src}
    mkdir -p src/github.com/gohugoio/
    tar xf $sources/v$version.tar.gz -C src/github.com/gohugoio/
    cd src/github.com/gohugoio/
    mv hugo-$version hugo
build      : |
    export GOPATH=$workdir/
    export PATH=$PATH:$GOPATH:$GOPATH/bin/
    # Workaround failing to fetch yaml.v2
    go get github.com/go-yaml/yaml
    mkdir -p .cache/govendor/gopkg.in/
    mv src/github.com/go-yaml/yaml .cache/govendor/gopkg.in/yaml.v2
    # Continue on with build
    cd src/github.com/gohugoio/hugo/
    make govendor
    make no-git-info
install    : |
    cd src/github.com/gohugoio/hugo/
    install -Dm00755 hugo $installdir/usr/bin/hugo
