name       : hugo
version    : 0.16
release    : 1
source     :
    - https://github.com/spf13/hugo/releases/download/v0.16/hugo_0.16_linux-64bit.tgz : 13e299dc45bea4fad5bdf8c2640305a5926e2acd02c3aa03b7864403e513920e
license    : Apache-2.0
component  : programming
summary    : Hugo is a static HTML and CSS website generator written in Go.
description: |
    Hugo is a static HTML and CSS website generator written in Go.
install    : |
    install -Dm00755 hugo $installdir/usr/bin/hugo
